image: debian:bullseye 

cache:
    paths:
        - apt-cache

before_script:
  - export APT_CACHE_DIR=${PWD}/apt-cache && mkdir -pv $APT_CACHE_DIR
  - echo -e 'deb http://ftp.uni-mainz.de/debian bullseye main\ndeb-src http://ftp.uni-mainz.de/debian bullseye main\ndeb http://ftp.uni-mainz.de/debian-security/ bullseye-security main\ndeb-src http://ftp.uni-mainz.de/debian-security/ bullseye-security main' > /etc/apt/sources.list  
  - apt-get update -qq
  - apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y -qq texlive texlive-latex-extra texlive-fonts-extra texlive-pstricks texlive-luatex texlive-science make latexmk shellcheck

stages:
    - build
    - test

build:Snakemake_HPC_Master:
  stage: build
  script:
    - make -C slides
    - mv snakemake-workflows/slides/Snakemake_HPC_Master.pdf Snakemake_HPC.pdf
  artifacts:
    paths:
        - Snakemake_HPC.pdf

#build:Snakemake_HPC_Master_tasks:
#  stage: build
#  script:
#    - make -C Snakemake_HPC_Master/tasks
#    - mv snakemake-workflows/tasks/exercises.pdf Snakemake_HPC_exercises.pdf
#  artifacts:
#    paths:
#      - Snakemake_HPC_exercises.pdf

