name: Build LaTex sources.

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: set up env
        uses: xu-cheng/latex-action@v3
        with:
          packages: python3-yaml
      - name: Compile Users Slide Set
        run: |
          ./render --master-tex Snakemake_HPC_Users.tex --configfile config/config_for_github.yaml ; 
      - name: Compile Creators Slide Set
        run: |
          ./render --master-tex Snakemake_HPC_Creators.tex --configfile config/config_for_github.yaml

      - name: Upload .pdf File
        uses: actions/upload-artifact@v3 
        with:
          name: Slides
          path: |
            slides/*.pdf
