name: Build LaTex sources.

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/xu-cheng/texlive-full:latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX sources
        run: make -C slides
      - name: Upload .pdf File
        uses: actions/upload-artifact@v3 
        with:
          name: Slides
          path: |
            slides/*.pdf
