name: Build LaTex sources.

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get install -y python3-yaml texlive-full texlive-latex-base
      - name: LaTeX compile  
        run: |
          ./render --master-tex Snakemake_HPC_Users.tex --configfile config/config_for_github.yaml ; 
          ./render --master-tex Snakemake_HPC_Creators.tex --configfile config/config_for_github.yaml

      - name: Upload .pdf File
        uses: actions/upload-artifact@v3 
        with:
          name: Slides
          path: |
            slides/*.pdf
