name: Build LaTex sources.

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get install -y python3-yaml 
             texlive 
             texlive-fonts-extra 
             texlive-latex-extra 
             texlive-luatex 
             texlive-pictures 
             texlive-plain-generic 
             texlive-pstricks 
             texlive-science 
             latexmk
        
      - name: LaTeX compile  
        run: |
          ./render --master-tex Snakemake_HPC_Users.tex --configfile config/config_for_github.yaml ; 
          ./render --master-tex Snakemake_HPC_Creators.tex --configfile config/config_for_github.yaml
          ./render --master-tex Snakemake_HPC_User_Creator_Combi.tex --configfile config/config_for_github.yaml
      
      - name: Certificate compile
        run: |
           cd certificates && ./certificate_generator --exportfile participant_test.csv --textemplate template_english.tex --config config.yaml

      - name: Upload .pdf File
        uses: actions/upload-artifact@v3 
        with:
          name: Slides
          path: |
            slides/*.pdf
