on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: "snakemake-hpc-teaching-material"
      - name: Create release
        id: create_release
        with:
          draft: false
          prerelease: false
          files: |
            slides/Snakemake_HPC_Users.pdf
            slides/Snakemake_HPC_Creators.pdf
            slides/Snakemake_HPC_User_Creator_Combi.pdf

